apiVersion: v1
kind: Service
metadata:
  name: f1-service
spec:
  type: ClusterIP
  selector:
    app: f1-app
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: f1-app
  template:
    metadata:
      labels:
        app: f1-app
    spec:
      # RULE: Forbidden on Master (So it goes to Workers)
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: f1-app
        image: fmaamoun/f1-vote-app:v1 
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
