# roles/master/tasks/main.yml
- name: Install K3s (Master)
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san {{ ansible_host }}" sh -
  args:
    creates: /usr/local/bin/k3s

- name: Wait for K3s to be ready
  pause:
    seconds: 10

- name: Get K3s Token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_base64
  run_once: true

- name: Decode and Store Token
  set_fact:
    k3s_token: "{{ k3s_token_base64['content'] | b64decode | trim }}"